### ISSUE TITLE
When starting the generator via Rider, plugins are searched in C:/Program Files/dotnet/plugins

### ISSUE THREAD

**Issue by janhohenheim** [messerli-informatik-ag/meta-generator#35]

**Comment by FreeApophis** [comment]
So, what is the current way to find the executables path working EVERYWHERE!?

**Comment by tautropfli** [comment]
There's `System.AppContext.BaseDirectory`. Keep in mind that that points to a temporary directory when doing a single file publish. See: https://github.com/dotnet/runtime/issues/3704
